name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --all-features
      - run: cargo test --release --all-features

  examples:
    name: Run Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - name: Run geometric example
        run: |
          ./target/release/bcurve \
            --mode geometric \
            --p0 0.01 --bin-step-bps 10 \
            --theta 0.6 \
            --target-supply 100000000 \
            --end-price 0.02 \
            --verbose \
            --no-draw \
            --out-dir out_ci_test
      - name: Check output exists
        run: |
          test -f out_ci_test/schedule.csv
          echo "✓ Schedule CSV generated successfully"

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all-features
      - run: cargo test --doc --all-features

  publish-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev fontconfig
          # Verify fontconfig installation and pkg-config setup
          pkg-config --list-all | grep fontconfig || true
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc || true
          ls -la /usr/lib/pkgconfig/fontconfig.pc || true
          ls -la /usr/share/pkgconfig/fontconfig.pc || true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish --dry-run
